name: LightDB CI

on:
  push:
    branches:
      - main
  release:
    types: [ published, created, edited ]
permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: install depends
        run: sudo apt update && sudo apt install redis-server -y && sudo /etc/init.d/redis-server start
      - name: set redis password
        run: redis-cli config set requirepass redis-password
      - name: Test with Gradle
        run: export JEDIS_PASSWORD=redis-password &&  chmod +x gradlew && ./gradlew clean test
