on:
  push:
    branches:
      - main
  release:
    types: [ published, created, edited ]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK'
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
      - name: 'Initialize Environment'
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
      - name: 'Download Gradle'
        run: |
          chmod +x ./gradlew
          ./gradlew tasks
      - name: 'Build Project'
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
      - name: 'Test Project'
        run: |
          chmod +x ./gradlew
          ./gradlew clean test
